### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by mherchel** [Gainesville-Barcamp/Gainesville-Barcamp#9]
- [x] Create Eventbrite page
- [x] Fix map scrolling issue
- [x] Link to parking map
- [x] Stub sessions page
- [x] Sponsors
- [ ] Sponsor prospectus PDF
- [x] Implement footer
- [x] Volunteer google form
- [x] Code of conduct
- [x] FAQ page
  - [x] Blank page design
  - [x] Come up with FAQ
- [x] Implement icons on buttons
- [x] Finalize prospectus HTML - make sure everything's correct
- [x] Contact Page
- [x] Location hyperlink needs to be changed on subpages - links to 404
